name: startup_corner
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.2
  cupertino_icons: ^1.0.8
  date_format: ^2.0.9
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.3
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.1.2
  photo_manager: ^3.6.4
  uuid: ^4.5.1
  video_player: ^2.9.2
  animated_text_kit: ^4.2.3
  url_launcher: ^6.3.1
  tflite_flutter: ^0.11.0
  flutter_gemini: ^3.0.0
  fl_chart: ^0.70.2
  rxdart: ^0.28.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/videos/
    - assets/logos/
    - assets/fonts/

 
